.DEFAULT_GOAL := help
COMPOSE = docker compose
API = $(COMPOSE) exec api

# ── Help ──────────────────────────────────────────────────────────────────────

.PHONY: help
help:
	@echo "Usage: make <target>"
	@echo ""
	@echo "  Dev"
	@echo "    dev        Start all services (detached)"
	@echo "    stop       Stop all services"
	@echo "    restart    Restart API container"
	@echo "    logs       Follow API logs"
	@echo "    shell      Open bash shell in API container"
	@echo "    ps         Show running containers"
	@echo ""
	@echo "  Testing"
	@echo "    test       Run full test suite"
	@echo "    test-fast  Run tests without coverage"
	@echo "    test-file  Run a specific file  (make test-file f=tests/...)"
	@echo "    test-k     Run tests matching name pattern  (make test-k k=test_login)"
	@echo ""
	@echo "  Code Quality"
	@echo "    lint       Run ruff linter"
	@echo "    format     Auto-format with ruff"
	@echo "    typecheck  Run mypy (strict)"
	@echo "    check      lint + typecheck"
	@echo ""
	@echo "  Database"
	@echo "    migrate    Apply pending migrations"
	@echo "    migration  Create autogenerated migration  (make migration msg='add users')"
	@echo "    rollback   Roll back last migration"
	@echo "    dbshell    Open psql shell"
	@echo ""
	@echo "  Setup"
	@echo "    keys       Generate RSA key pair for JWT"
	@echo "    reset-seed Hard-delete users/roles and rebuild canonical seed data"
	@echo "    seed       Create default system users"
	@echo "    env        Copy .env.example to .env (if not exists)"
	@echo "    install    Install dev dependencies locally"

# ── Dev ───────────────────────────────────────────────────────────────────────

.PHONY: dev
dev:
	$(COMPOSE) up -d

.PHONY: stop
stop:
	$(COMPOSE) down

.PHONY: restart
restart:
	$(COMPOSE) restart api

.PHONY: logs
logs:
	$(COMPOSE) logs -f api

.PHONY: shell
shell:
	$(API) bash

.PHONY: ps
ps:
	$(COMPOSE) ps

# ── Testing ───────────────────────────────────────────────────────────────────

.PHONY: test
test:
	$(API) pytest tests/ -v --cov=app --cov-report=term-missing

.PHONY: test-fast
test-fast:
	$(API) pytest tests/ -v --no-cov -q

.PHONY: test-file
test-file:
	$(API) pytest $(f) -v --no-cov

.PHONY: test-k
test-k:
	$(API) pytest tests/ -v --no-cov -k "$(k)"

# ── Code Quality ──────────────────────────────────────────────────────────────

.PHONY: lint
lint:
	$(API) ruff check app/ tests/ scripts/
	$(API) ruff format --check app/ tests/ scripts/

.PHONY: format
format:
	$(API) ruff format app/ tests/ scripts/
	$(API) ruff check --fix app/ tests/ scripts/

.PHONY: typecheck
typecheck:
	$(API) mypy app/

.PHONY: check
check: lint typecheck

# ── Database ──────────────────────────────────────────────────────────────────

.PHONY: migrate
migrate:
	$(API) alembic upgrade head

.PHONY: migration
migration:
	$(API) alembic revision --autogenerate -m "$(msg)"

.PHONY: rollback
rollback:
	$(API) alembic downgrade -1

.PHONY: dbshell
dbshell:
	$(COMPOSE) exec db psql -U $${POSTGRES_USER:-postgres} $${POSTGRES_DB:-appdb}

# ── Setup ─────────────────────────────────────────────────────────────────────

.PHONY: keys
keys:
	@mkdir -p keys
	@openssl genrsa -out keys/private.pem 4096
	@openssl rsa -in keys/private.pem -pubout -out keys/public.pem
	@echo "RSA key pair generated in keys/"

.PHONY: seed
seed:
	$(API) python -c "import asyncio; from app.admin.seed import create_default_app_user, create_default_superadmin; asyncio.run(create_default_superadmin()); asyncio.run(create_default_app_user())"

.PHONY: reset-seed
reset-seed:
	$(API) python scripts/reset_system_state.py

.PHONY: env
env:
	@test -f .env || (cp .env.example .env && echo ".env created from .env.example")

.PHONY: install
install:
	pip install -r requirements.txt -r requirements-dev.txt
