"""add expires_at index to api_keys

Revision ID: 68d9fd073c84
Revises: 20260412_03
Create Date: 2026-04-12 13:49:55.937539
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68d9fd073c84'
down_revision: Union[str, None] = '20260412_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_api_keys_expires_at', 'api_keys', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_keys_expires_at', table_name='api_keys')
    # ### end Alembic commands ###
