"""add composite indexes

Revision ID: ba36edc854a4
Revises: a7c2e9f04b31
Create Date: 2026-04-01 13:19:21.824177
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba36edc854a4'
down_revision: Union[str, None] = 'a7c2e9f04b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Performans için composite index'ler ekler."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_keys_key_prefix', table_name='api_keys')
    op.create_index('ix_api_keys_user_active', 'api_keys', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_oauth_user_provider', 'oauth_accounts', ['user_id', 'provider'], unique=False)
    op.create_unique_constraint('uq_oauth_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    op.drop_index('ix_totp_backup_codes_user_active', table_name='totp_backup_codes', postgresql_where='(is_used = false)')
    op.create_index('ix_totp_backup_user_used', 'totp_backup_codes', ['user_id', 'is_used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Eklenen composite index'leri kaldırır."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_totp_backup_user_used', table_name='totp_backup_codes')
    op.create_index('ix_totp_backup_codes_user_active', 'totp_backup_codes', ['user_id'], unique=False, postgresql_where='(is_used = false)')
    op.drop_constraint('uq_oauth_provider_user', 'oauth_accounts', type_='unique')
    op.drop_index('ix_oauth_user_provider', table_name='oauth_accounts')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_action_created', table_name='audit_logs')
    op.drop_index('ix_api_keys_user_active', table_name='api_keys')
    op.create_index('ix_api_keys_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    # ### end Alembic commands ###
