"""Infrastructure port/protocol tanımları."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from fastapi import UploadFile


class RedisPort(Protocol):
    """Servis katmanının ihtiyaç duyduğu Redis sözleşmesi."""

    async def get(self, key: str) -> str | None: ...
    async def setex(self, key: str, ttl: int, value: str) -> None: ...
    async def set(self, key: str, value: str, ex: int | None = None) -> None: ...
    async def delete(self, *keys: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def sismember(self, key: str, member: str) -> bool: ...
    async def srem(self, key: str, member: str) -> None: ...
    async def sadd(self, key: str, *members: str) -> None: ...
    async def expire(self, key: str, ttl: int) -> None: ...
    async def ttl(self, key: str) -> int: ...
    async def scan(self, cursor: int, match: str, count: int) -> tuple[int, list[str]]: ...
    async def ping(self) -> bool: ...


class TaskQueuePort(Protocol):
    """Background queue sözleşmesi."""

    async def enqueue(self, task_func: Any, *args: Any, **kwargs: Any) -> None: ...


class WebSocketNotifierPort(Protocol):
    """Realtime bildirim sözleşmesi."""

    async def notify_user(self, user_id: str, payload: dict[str, object]) -> None: ...


class StoragePort(Protocol):
    """Dosya saklama sözleşmesi."""

    async def upload(self, file: UploadFile, folder: str = "") -> str: ...
    async def delete(self, key: str) -> None: ...
    async def get_url(self, key: str, expires_in: int = 3600) -> str: ...
